// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Nutrients.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Nutrients _$NutrientsFromJson(Map<String, dynamic> json) {
  return Nutrients(
      (json['Calories'] as num)?.toDouble(),
      (json['Fat'] as num)?.toDouble(),
      (json['Protein'] as num)?.toDouble(),
      (json['Carbs'] as num)?.toDouble(),
      (json['Alcohol'] as num)?.toDouble(),
      (json['Caffeine'] as num)?.toDouble(),
      (json['Copper'] as num)?.toDouble(),
      (json['Calcium'] as num)?.toDouble(),
      (json['Choline'] as num)?.toDouble(),
      (json['Cholesterol'] as num)?.toDouble(),
      (json['Fluoride'] as num)?.toDouble(),
      (json['SaturatedFat'] as num)?.toDouble(),
      (json['VitaminA'] as num)?.toDouble(),
      (json['VitaminC'] as num)?.toDouble(),
      (json['VitaminD'] as num)?.toDouble(),
      (json['VitaminE'] as num)?.toDouble(),
      (json['VitaminK'] as num)?.toDouble(),
      (json['VitaminB1'] as num)?.toDouble(),
      (json['VitaminB2'] as num)?.toDouble(),
      (json['VitaminB3'] as num)?.toDouble(),
      (json['VitaminB5'] as num)?.toDouble(),
      (json['VitaminB6'] as num)?.toDouble(),
      (json['VitaminB12'] as num)?.toDouble(),
      (json['Fiber'] as num)?.toDouble(),
      (json['Folate'] as num)?.toDouble(),
      (json['FolicAcid'] as num)?.toDouble(),
      (json['Iodine'] as num)?.toDouble(),
      (json['Iron'] as num)?.toDouble(),
      (json['Magnesium'] as num)?.toDouble(),
      (json['Manganese'] as num)?.toDouble(),
      (json['Phosphorous'] as num)?.toDouble(),
      (json['Potassium'] as num)?.toDouble(),
      (json['Selenium'] as num)?.toDouble(),
      (json['Sodium'] as num)?.toDouble(),
      (json['Sugar'] as num)?.toDouble(),
      (json['Zinc'] as num)?.toDouble());
}

Map<String, dynamic> _$NutrientsToJson(Nutrients instance) => <String, dynamic>{
      'Calories': instance.calories,
      'Fat': instance.fat,
      'Protein': instance.protein,
      'Carbs': instance.carbs,
      'Alcohol': instance.alcohol,
      'Caffeine': instance.caffeine,
      'Copper': instance.copper,
      'Calcium': instance.calcium,
      'Choline': instance.choline,
      'Cholesterol': instance.cholesterol,
      'Fluoride': instance.fluoride,
      'SaturatedFat': instance.saturatedFat,
      'VitaminA': instance.vitaminA,
      'VitaminC': instance.vitaminC,
      'VitaminD': instance.vitaminD,
      'VitaminE': instance.vitaminE,
      'VitaminK': instance.vitaminK,
      'VitaminB1': instance.vitaminB1,
      'VitaminB2': instance.vitaminB2,
      'VitaminB3': instance.vitaminB3,
      'VitaminB5': instance.vitaminB5,
      'VitaminB6': instance.vitaminB6,
      'VitaminB12': instance.vitaminB12,
      'Fiber': instance.fiber,
      'Folate': instance.folate,
      'FolicAcid': instance.folicAcid,
      'Iodine': instance.iodine,
      'Iron': instance.iron,
      'Magnesium': instance.magnesium,
      'Manganese': instance.manganese,
      'Phosphorous': instance.phosphorous,
      'Potassium': instance.potassium,
      'Selenium': instance.selenium,
      'Sodium': instance.sodium,
      'Sugar': instance.sugar,
      'Zinc': instance.zinc
    };
